/* Generated by tools/ds_gen.py from the Prose 2000 v3.4.1 ROM dumps, and maintained by hand from then on: the
 * tables may be edited (names, types, splits), and ds_image_check checks that they still build the ROM's
 * DS:0000-AEA9 byte for byte. Design: docs/superpowers/specs/2026-09-28-ds-structured-tables-design.md */
#include "prose_ds_tables.h"

/* DS:0000-000B six RAM addresses (EBF0 C202 DD80 DBCC EE7A EE5C); no reader found [opaque] */
const uint16_t prose_ds_ram_ptrs[6] = {
	0xEBF0, 0xC202, 0xDD80, 0xDBCC, 0xEE7A, 0xEE5C, /* DS:0000 */
};
PROSE_DS_ASSERT(prose_ds_ram_ptrs, sizeof prose_ds_ram_ptrs == 12);

/* DS:000C-001B rom_checksum: byte sums of ROM lanes 0-7, lanes 0-1 unused (REFERENCE §14) [full] */
const uint16_t prose_ds_lane_sums[8] = {
	0x0000, 0x0000, 0xCEEF, 0x88A8, 0x68DB, 0x1EA4, 0xE00B, 0xAA75, /* DS:000C */
};
PROSE_DS_ASSERT(prose_ds_lane_sums, sizeof prose_ds_lane_sums == 16);

/* DS:001C-001F no reader found [opaque] */
const uint8_t prose_ds_ds_001c[4] = {
	0xF5, 0x1F, 0x8B, 0x55, /* DS:001C */
};
PROSE_DS_ASSERT(prose_ds_ds_001c, sizeof prose_ds_ds_001c == 4);

/* DS:0020-002F the bit each node kind sets in a stage window (REFERENCE §15.1) [full] */
const uint16_t prose_ds_stage_accept[8] = {
	0x0010, 0x0001, 0x0002, 0x0004, 0x0008, 0x0020, 0x0000, 0x0000, /* DS:0020 */
};
PROSE_DS_ASSERT(prose_ds_stage_accept, sizeof prose_ds_stage_accept == 16);

/* DS:0030-0047 a symmetric curve 0252 ... 7ED8 ... 0252; no v3 reader [opaque] */
const uint16_t prose_ds_ds_0030[12] = {
	0x0252, 0x12D2, 0x2FF4, 0x5514, 0x6E16, 0x7ED8, 0x7ED8, 0x6E16, /* DS:0030 */
	0x5514, 0x2FF4, 0x12D2, 0x0252, /* DS:0040 */
};
PROSE_DS_ASSERT(prose_ds_ds_0030, sizeof prose_ds_ds_0030 == 24);

/* DS:03A8-03A9 TR_ATTR_PTR: the text-rule attribute record in RAM (DS:DB04) [full] */
const uint16_t prose_ds_tr_attr_ptr[1] = {
	0xDB04, /* DS:03A8 */
};
PROSE_DS_ASSERT(prose_ds_tr_attr_ptr, sizeof prose_ds_tr_attr_ptr == 2);

/* DS:03AA-03B8 INT8_STUB: 8086 code copied to 0000:0024 for ESC[nL (REFERENCE §2, §8.2) [full] */
const uint8_t prose_ds_int8_stub[15] = {
	0xFA, 0xBB, 0x00, 0x03, 0x8E, 0xC3, 0x26, 0xA2, 0x02, 0x04, 0xEA, 0x00, 0x00, 0xFF, 0xFF, /* DS:03AA */
};
PROSE_DS_ASSERT(prose_ds_int8_stub, sizeof prose_ds_int8_stub == 15);

/* DS:03B9-03B9 padding [opaque] */
const uint8_t prose_ds_ds_03b9[1] = {
	0xFF, /* DS:03B9 */
};
PROSE_DS_ASSERT(prose_ds_ds_03b9, sizeof prose_ds_ds_03b9 == 1);

/* DS:03BA-03CD SPEED_CAP: the highest speed for each fast-read level (REFERENCE §8.2) [full] */
const uint16_t prose_ds_speed_cap[10] = {
	25, 20, 16, 13, 13, 13, 13, 13, /* DS:03BA */
	13, 13, /* DS:03CA */
};
PROSE_DS_ASSERT(prose_ds_speed_cap, sizeof prose_ds_speed_cap == 20);

/* DS:03CE-03CE IDENTITY: the ESC[E answer, 34 [full] */
const uint8_t prose_ds_identity[1] = {
	34, /* DS:03CE */
};
PROSE_DS_ASSERT(prose_ds_identity, sizeof prose_ds_identity == 1);

/* DS:03CF-03CF padding [opaque] */
const uint8_t prose_ds_ds_03cf[1] = {
	0xFF, /* DS:03CF */
};
PROSE_DS_ASSERT(prose_ds_ds_03cf, sizeof prose_ds_ds_03cf == 1);
