/* Generated by tools/ds_gen.py from the Prose 2000 v3.4.1 ROM dumps, and maintained by hand from then on: the
 * tables may be edited (names, types, splits), and ds_image_check checks that they still build the ROM's
 * DS:0000-AEA9 byte for byte. Design: docs/superpowers/specs/2026-09-28-ds-structured-tables-design.md */
#include "prose_ds_tables.h"

const prose_ds_span prose_ds_layout[] = {
	{0x0000, sizeof prose_ds_raw_0000, prose_ds_raw_0000, "raw_0000"},
	{0x03D0, sizeof prose_ds_raw_03d0, prose_ds_raw_03d0, "raw_03d0"},
	{0x212E, sizeof prose_ds_raw_212e, prose_ds_raw_212e, "raw_212e"},
	{0x52F8, sizeof prose_ds_raw_52f8, prose_ds_raw_52f8, "raw_52f8"},
	{0x6052, sizeof prose_ds_raw_6052, prose_ds_raw_6052, "raw_6052"},
	{0x626C, sizeof prose_ds_raw_626c, prose_ds_raw_626c, "raw_626c"},
	{0x9BE8, sizeof prose_ds_raw_9be8, prose_ds_raw_9be8, "raw_9be8"},
};
const unsigned prose_ds_layout_count = sizeof prose_ds_layout / sizeof prose_ds_layout[0];
