/* Generated by tools/rom_extract.py from the Prose 2000 ROM dumps; do not edit.
 * Sources (SHA-1):
 *   549ef1aa28d5664d4198cbc1826b31020d6c4870  v3.4.1__2000__2.u22
 *   2b90b3c227012f2085719e6283da08afb36f394f  v3.4.1__2000__3.u45
 *   e1d3e7ba309b29a9c3edbe3d22becf82eae50a31  v3.4.1__2000__0.u21
 *   6512a8c2641e032ef6bb0889490d82f5d4399575  v3.4.1__2000__1.u44
 *   6e184747db2f26e45d0e02907105ff192e51baba  v3.12__8-9-88__dsp_data.u29
 */
#ifndef PROSE_DATA_H
#define PROSE_DATA_H

#include <stdint.h>

#define PROSE_LEXICON_BASE 0xE9000u /* linear address of prose_lexicon[0] */
extern const uint8_t prose_lexicon[0x968E];
#define PROSE_DS_DATA_BASE 0xF4100u /* linear address of prose_ds_data[0] */
extern const uint8_t prose_ds_data[0xAEAA];
/* the byte sums of the 32 KB lanes 2-7 of D0000-FFFFF (D000 even, D000 odd, E000 even, ... F000 odd), as
   the boot ROM check (rom_checksum D33B3) computes them */
extern const uint16_t prose_rom_lane_sums[6];
/* the DSP data ROM (v3.12), 512 words in address order */
extern const uint16_t prose_dsp_data_rom[512];

#endif
