/* Generated by tools/ds_gen.py from the Prose 2000 v3.4.1 ROM dumps, and maintained by hand from then on: the
 * tables may be edited (names, types, splits), and ds_image_check checks that they still build the ROM's
 * DS:0000-AEA9 byte for byte. Design: docs/superpowers/specs/2026-09-28-ds-structured-tables-design.md */
#ifndef PROSE_DS_TABLES_H
#define PROSE_DS_TABLES_H

#include <stdint.h>

#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ != __ORDER_LITTLE_ENDIAN__
#error "the data-segment tables are copied into the ROM image as they lie in memory: little-endian only"
#endif

#define PROSE_DS_DATA_BASE 0xF4100u /* linear address of DS:0000 */
#define PROSE_DS_SIZE 0xAEAAu       /* DS:0000-AEA9 is ROM data */
#define PROSE_DS_FNV1A64 0xFC86CABA8C589DDDull /* FNV-1a (64-bit) of the ROM's DS:0000-AEA9 */

/* compile-time check (C99) */
#define PROSE_DS_ASSERT(name, cond) typedef char prose_ds_assert_##name[(cond) ? 1 : -1]
/* a 16-bit value as two bytes, little-endian, inside a byte table */
#define PROSE_W(x) (uint8_t)((x) & 0xFF), (uint8_t)(((x) >> 8) & 0xFF)

/* where each table lies; prose_rom_builtin copies them into the ROM image (ds_layout.c) */
typedef struct {
	uint16_t off, size;
	const void *data;
	const char *name;
} prose_ds_span;
extern const prose_ds_span prose_ds_layout[];
extern const unsigned prose_ds_layout_count;

/* LTS condition / pass-on pair: a rule's +6 tests LTS_STATE and LTS_CLASS (bit 15 of a word: none / any present); +8 gives the flags and the class passed on (lts_class_match, lts_rules) */
typedef struct {
	uint16_t state;
	uint16_t cls;
} prose_lts_pair;
PROSE_DS_ASSERT(prose_lts_pair, sizeof(prose_lts_pair) == 4);

/* letter-to-sound rule: letters (reversed), phoneme output, right context pattern, condition pair, pass-on pair (lts_rules D78AE, REFERENCE §15.3) */
typedef struct {
	uint16_t letters;
	uint16_t output;
	uint16_t pattern;
	uint16_t cond;
	uint16_t pass_on;
} prose_lts_rule;
PROSE_DS_ASSERT(prose_lts_rule, sizeof(prose_lts_rule) == 10);

/* generator action: op, voice mask, value, RAM address (DS:DE2E-EBCA) it acts on (paramgen_rule_action, REFERENCE §12.5) */
typedef struct {
	uint8_t op;
	uint8_t voices;
	int16_t value;
	uint16_t addr;
} prose_pg_action;
PROSE_DS_ASSERT(prose_pg_action, sizeof(prose_pg_action) == 6);

/* far pointer (offset, segment) to a generator routine; 0:0 ends a list */
typedef struct {
	uint16_t off;
	uint16_t seg;
} prose_far_ptr;
PROSE_DS_ASSERT(prose_far_ptr, sizeof(prose_far_ptr) == 4);

/* generator rule: condition, action list, routine list, second action list (paramgen_apply_rules, REFERENCE §12.5) */
typedef struct {
	uint16_t cond;
	uint16_t actions;
	uint16_t routines;
	uint16_t actions_b;
} prose_pg_rule;
PROSE_DS_ASSERT(prose_pg_rule, sizeof(prose_pg_rule) == 8);

/* consonant targets of one parameter (AF ... AB): bytes for phoneme indices 29-58, then the block's address minus 29, which the generator indexes by phoneme */
typedef struct {
	uint8_t target[30];
	uint16_t base;
} prose_cons_block;
PROSE_DS_ASSERT(prose_cons_block, sizeof(prose_cons_block) == 32);

/* affix record: string (suffixes reversed), context pattern, 1 = look the stem up, word class, stress or AFFIX_CODE, 0-terminated list of records to try next (affix_match E5152) */
typedef struct {
	uint16_t string;
	uint16_t pattern;
	uint8_t lookup;
	uint8_t word_class;
	uint8_t code;
	uint8_t pad;
	uint16_t next;
} prose_affix;
PROSE_DS_ASSERT(prose_affix, sizeof(prose_affix) == 10);

/* the tables, in DS order: offset, then the array (src/data/ds_<file>.c) */
#define PROSE_DS_RAM_PTRS 0x0000u
extern const uint16_t prose_ds_ram_ptrs[6];
#define PROSE_DS_LANE_SUMS 0x000Cu
extern const uint16_t prose_ds_lane_sums[8];
#define PROSE_DS_DS_001C 0x001Cu
extern const uint8_t prose_ds_ds_001c[4];
#define PROSE_DS_STAGE_ACCEPT 0x0020u
extern const uint16_t prose_ds_stage_accept[8];
#define PROSE_DS_DS_0030 0x0030u
extern const uint16_t prose_ds_ds_0030[12];
#define PROSE_DS_CLASS_MASKS 0x0048u
extern const uint16_t prose_ds_class_masks[48];
#define PROSE_DS_FEATURES 0x00A8u
extern const uint8_t prose_ds_features[6][128];
#define PROSE_DS_TR_ATTR_PTR 0x03A8u
extern const uint16_t prose_ds_tr_attr_ptr[1];
#define PROSE_DS_INT8_STUB 0x03AAu
extern const uint8_t prose_ds_int8_stub[15];
#define PROSE_DS_DS_03B9 0x03B9u
extern const uint8_t prose_ds_ds_03b9[1];
#define PROSE_DS_SPEED_CAP 0x03BAu
extern const uint16_t prose_ds_speed_cap[10];
#define PROSE_DS_IDENTITY 0x03CEu
extern const uint8_t prose_ds_identity[1];
#define PROSE_DS_DS_03CF 0x03CFu
extern const uint8_t prose_ds_ds_03cf[1];
#define PROSE_DS_TR_PATTERNS 0x03D0u
extern const uint8_t prose_ds_tr_patterns[3544];
#define PROSE_DS_TR_LIST_ITEMS 0x11A8u
extern const uint16_t prose_ds_tr_list_items[326];
#define PROSE_DS_TR_LISTS 0x1434u
extern const uint16_t prose_ds_tr_lists[21];
#define PROSE_DS_TR_WORD_CHARS 0x145Eu
extern const uint8_t prose_ds_tr_word_chars[16];
#define PROSE_DS_TR_PROGRAM 0x146Eu
extern const uint8_t prose_ds_tr_program[3045];
#define PROSE_DS_TR_STRINGS 0x2053u
extern const uint8_t prose_ds_tr_strings[219];
#define PROSE_DS_LETTER_STATES 0x212Eu
extern const uint8_t prose_ds_letter_states[3][12];
#define PROSE_DS_PHONEME_STATES 0x2152u
extern const uint8_t prose_ds_phoneme_states[4][8];
#define PROSE_DS_ENTRY_ADJUST 0x2172u
extern const uint8_t prose_ds_entry_adjust[3][17];
#define PROSE_DS_DS_21A5 0x21A5u
extern const uint8_t prose_ds_ds_21a5[1];
#define PROSE_DS_LTS_HEAD 0x21A6u
extern const uint8_t prose_ds_lts_head[6];
#define PROSE_DS_LTS_OUTPUTS 0x21ACu
extern const uint8_t prose_ds_lts_outputs[1908];
#define PROSE_DS_LTS_LETTERS 0x2920u
extern const uint8_t prose_ds_lts_letters[1297];
#define PROSE_DS_LTS_PATTERNS 0x2E31u
extern const uint8_t prose_ds_lts_patterns[1457];
#define PROSE_DS_LTS_PAIRS 0x33E2u
extern const prose_lts_pair prose_ds_lts_pairs[263];
#define PROSE_DS_LTS_RULES 0x37FEu
extern const prose_lts_rule prose_ds_lts_rules[685];
#define PROSE_DS_LTS_LETTER_RULES 0x52C0u
extern const uint16_t prose_ds_lts_letter_rules[28];
#define PROSE_DS_VOICE_SCALE 0x52F8u
extern const uint16_t prose_ds_voice_scale[8];
#define PROSE_DS_VOICE_SRC 0x5308u
extern const uint8_t prose_ds_voice_src[32];
#define PROSE_DS_VOICE_PITCH 0x5328u
extern const uint16_t prose_ds_voice_pitch[8];
#define PROSE_DS_DS_5338 0x5338u
extern const uint16_t prose_ds_ds_5338[8];
#define PROSE_DS_VOICE_F4 0x5348u
extern const uint16_t prose_ds_voice_f4[8];
#define PROSE_DS_VOICE_F4_MAX 0x5358u
extern const uint16_t prose_ds_voice_f4_max[8];
#define PROSE_DS_VOICE_FRAME 0x5368u
extern const uint16_t prose_ds_voice_frame[8][8];
#define PROSE_DS_T_JITTER_DEPTH 0x53E8u
extern const uint16_t prose_ds_t_jitter_depth[16];
#define PROSE_DS_T_SHIMMER_DEPTH 0x5408u
extern const uint16_t prose_ds_t_shimmer_depth[16];
#define PROSE_DS_T_JITTER 0x5428u
extern const int16_t prose_ds_t_jitter[64];
#define PROSE_DS_T_VGAIN_SCALE 0x54A8u
extern const uint16_t prose_ds_t_vgain_scale[32];
#define PROSE_DS_T_VGAIN 0x54E8u
extern const uint16_t prose_ds_t_vgain[126];
#define PROSE_DS_T_AV_BY_P18 0x55E4u
extern const uint16_t prose_ds_t_av_by_p18[32];
#define PROSE_DS_T_AV_BY_P19 0x5624u
extern const uint16_t prose_ds_t_av_by_p19[16];
#define PROSE_DS_DSP_BOOT 0x5644u
extern const uint16_t prose_ds_dsp_boot[9];
#define PROSE_DS_T_TEMPLATE 0x5656u
extern const uint16_t prose_ds_t_template[40];
#define PROSE_DS_T_NZ_GAIN 0x56A6u
extern const uint16_t prose_ds_t_nz_gain[18];
#define PROSE_DS_T_EXP1 0x56CAu
extern const uint16_t prose_ds_t_exp1[128];
#define PROSE_DS_T_EXP2 0x57CAu
extern const uint16_t prose_ds_t_exp2[128];
#define PROSE_DS_T_COS 0x58CAu
extern const int16_t prose_ds_t_cos[512];
#define PROSE_DS_T_DB 0x5CCAu
extern const uint16_t prose_ds_t_db[213];
#define PROSE_DS_T_PAR_CORR1 0x5E74u
extern const uint16_t prose_ds_t_par_corr1[121];
#define PROSE_DS_T_PAR_CORR2 0x5F66u
extern const uint16_t prose_ds_t_par_corr2[118];
#define PROSE_DS_PAUSE_SCALE 0x6052u
extern const uint16_t prose_ds_pause_scale[26];
#define PROSE_DS_SPEED_PCT 0x6086u
extern const uint16_t prose_ds_speed_pct[26];
#define PROSE_DS_BREAK_MASK 0x60BAu
extern const uint8_t prose_ds_break_mask[30];
#define PROSE_DS_CLUSTER_PCT 0x60D8u
extern const uint16_t prose_ds_cluster_pct[4];
#define PROSE_DS_LOW_MAX 0x60E0u
extern const uint16_t prose_ds_low_max[22];
#define PROSE_DS_TRACK_DEFAULT 0x610Cu
extern const uint8_t prose_ds_track_default[22];
#define PROSE_DS_TEST_ROWS 0x6122u
extern const uint8_t prose_ds_test_rows[10][22];
#define PROSE_DS_LOW_DEFAULT 0x61FEu
extern const uint8_t prose_ds_low_default[22];
#define PROSE_DS_AV_BY_F0 0x6214u
extern const uint8_t prose_ds_av_by_f0[16];
#define PROSE_DS_DEMO_TEXT 0x6224u
extern const uint8_t prose_ds_demo_text[70];
#define PROSE_DS_DEMO_TEXT_PTR 0x626Au
extern const uint16_t prose_ds_demo_text_ptr[1];
#define PROSE_DS_PG_CONDITIONS 0x626Cu
extern const uint8_t prose_ds_pg_conditions[266];
#define PROSE_DS_PG_ACTIONS 0x6376u
extern const prose_pg_action prose_ds_pg_actions[632];
#define PROSE_DS_DS_7246 0x7246u
extern const uint8_t prose_ds_ds_7246[24];
#define PROSE_DS_PG_ACTION_LISTS 0x725Eu
extern const uint16_t prose_ds_pg_action_lists[752];
#define PROSE_DS_PG_ROUTINES 0x783Eu
extern const prose_far_ptr prose_ds_pg_routines[86];
#define PROSE_DS_PG_RULES 0x7996u
extern const prose_pg_rule prose_ds_pg_rules[621];
#define PROSE_DS_PG_GROUPS 0x8CFEu
extern const uint16_t prose_ds_pg_groups[88];
#define PROSE_DS_PG_GROUP_COUNTS 0x8DAEu
extern const uint8_t prose_ds_pg_group_counts[88];
#define PROSE_DS_PG_PAIR_ROWS 0x8E06u
extern const uint8_t prose_ds_pg_pair_rows[24][58];
#define PROSE_DS_PG_PAIR_ROW_PTRS 0x9376u
extern const uint16_t prose_ds_pg_pair_row_ptrs[58];
#define PROSE_DS_PHONEME_MAP 0x93EAu
extern const uint8_t prose_ds_phoneme_map[96];
#define PROSE_DS_PHONEME_MAP_PTR 0x944Au
extern const uint16_t prose_ds_phoneme_map_ptr[1];
#define PROSE_DS_TARGETS 0x944Cu
extern const uint8_t prose_ds_targets[8][58];
#define PROSE_DS_DS_961C 0x961Cu
extern const uint16_t prose_ds_ds_961c[58];
#define PROSE_DS_OFFGLIDES 0x9690u
extern const uint8_t prose_ds_offglides[6][18];
#define PROSE_DS_DS_96FC 0x96FCu
extern const uint16_t prose_ds_ds_96fc[18];
#define PROSE_DS_ONGLIDE_HOLD 0x9720u
extern const uint16_t prose_ds_onglide_hold[18];
#define PROSE_DS_DS_9744 0x9744u
extern const uint8_t prose_ds_ds_9744[18];
#define PROSE_DS_CONS_TARGETS 0x9756u
extern const prose_cons_block prose_ds_cons_targets[8];
#define PROSE_DS_FORMANT_DUR 0x9856u
extern const uint8_t prose_ds_formant_dur[8];
#define PROSE_DS_NEUTRAL_F1 0x985Eu
extern const uint16_t prose_ds_neutral_f1[3];
#define PROSE_DS_LOCUS_WEIGHTS 0x9864u
extern const uint16_t prose_ds_locus_weights[4][4];
#define PROSE_DS_REDUCTION 0x9884u
extern const uint16_t prose_ds_reduction[16];
#define PROSE_DS_DEFAULT_DUR 0x98A4u
extern const uint8_t prose_ds_default_dur[22];
#define PROSE_DS_NASAL_FN 0x98BAu
extern const uint8_t prose_ds_nasal_fn[6];
#define PROSE_DS_NASAL_FN_PTR 0x98C0u
extern const uint16_t prose_ds_nasal_fn_ptr[1];
#define PROSE_DS_NEXT_CLASS 0x98C2u
extern const uint8_t prose_ds_next_class[58];
#define PROSE_DS_STOP_LOCUS_ROWS 0x98FCu
extern const uint8_t prose_ds_stop_locus_rows[9];
#define PROSE_DS_STOP_LOCI 0x9905u
extern const uint8_t prose_ds_stop_loci[6][72];
#define PROSE_DS_RAMPS 0x9AB5u
extern const uint8_t prose_ds_ramps[233];
#define PROSE_DS_RAMP_PTRS 0x9B9Eu
extern const uint16_t prose_ds_ramp_ptrs[21];
#define PROSE_DS_BIT_MASKS 0x9BC8u
extern const uint16_t prose_ds_bit_masks[16];
#define PROSE_DS_SUFFIX_POOL 0x9BE8u
extern const uint8_t prose_ds_suffix_pool[1572];
#define PROSE_DS_SUFFIX_RECORDS 0xA20Cu
extern const prose_affix prose_ds_suffix_records[94];
#define PROSE_DS_SUFFIX_LISTS 0xA5B8u
extern const uint16_t prose_ds_suffix_lists[111];
#define PROSE_DS_SUFFIXES 0xA696u
extern const uint16_t prose_ds_suffixes[26];
#define PROSE_DS_PREFIX_POOL 0xA6CAu
extern const uint8_t prose_ds_prefix_pool[916];
#define PROSE_DS_PREFIX_RECORDS 0xAA5Eu
extern const prose_affix prose_ds_prefix_records[60];
#define PROSE_DS_PREFIX_LISTS 0xACB6u
extern const uint16_t prose_ds_prefix_lists[77];
#define PROSE_DS_PREFIXES 0xAD50u
extern const uint16_t prose_ds_prefixes[26];
#define PROSE_DS_INH 0xAD84u
extern const uint8_t prose_ds_inh[96];
#define PROSE_DS_INH_PTR 0xADE4u
extern const uint16_t prose_ds_inh_ptr[1];
#define PROSE_DS_MIN 0xADE6u
extern const uint8_t prose_ds_min[96];
#define PROSE_DS_MIN_PTR 0xAE46u
extern const uint16_t prose_ds_min_ptr[1];
#define PROSE_DS_PLACE 0xAE48u
extern const uint8_t prose_ds_place[96];
#define PROSE_DS_PLACE_PTR 0xAEA8u
extern const uint16_t prose_ds_place_ptr[1];

#endif
