/* Generated by tools/rom_extract.py --v1 from the Prose 2000 v1.1 ROM dumps; do not edit.
 * Sources (SHA-1):
 *   2d4eb96360adac54d4f0110595bfaf682280c1ca  v1.1__6__speech__plus__=c=1983.am2764.6.u24
 *   55ed59ad1cad154804dbeeebed98f062783c33c3  v1.1__7__speech__plus__=c=1983.am2764.7.u47
 *   0b73561b52b388b740fabf07ada2d70a52f22037  v1.1__8__speech__plus__=c=1983.am2764.8.u25
 *   7655fc55b577821e0bd8bf81fb74b8a20b1df098  v1.1__9__speech__plus__=c=1983.am2764.9.u48
 *   8e33c69dfc413aea95f166b08902ad97b1e3e980  v1.1__10__speech__plus__=c=1983.am2764.10.u26
 *   769f2f8696c7b6907706466aa9ab7a897ed9f889  v1.1__11__speech__plus__=c=1983.am2764.11.u49
 *   d296b1d347c03e6123c38c208ead25b1f43b9859  v1.1__12__speech__plus__=c=1983.am2764.12.u27
 *   93230c2fede5095f56e10d20ea36a5a45a1e7356  v1.1__13__speech__plus__=c=1983.am2764.13.u50
 *   5dfae2c5079d89f791c9d7166f9504231a464203  v1.1__14__speech__plus__=c=1983.am2764.14.u28
 *   72130fe45c3fd3de7cf794936dc68ed2d4193daf  v1.1__15__speech__plus__=c=1983.am2764.15.u51
 */
#ifndef PROSE_V1_DATA_H
#define PROSE_V1_DATA_H

#include <stdint.h>

#define PROSE_V1_DS_DATA_BASE 0xF7660u /* linear address of prose_v1_ds_data[0] */
extern const uint8_t prose_v1_ds_data[0x89A0];

#endif
