/* Generated by tools/ds_gen.py from the Prose 2000 v3.4.1 ROM dumps, and maintained by hand from then on: the
 * tables may be edited (names, types, splits), and ds_image_check checks that they still build the ROM's
 * DS:0000-AEA9 byte for byte. Design: docs/superpowers/specs/2026-09-28-ds-structured-tables-design.md */
#ifndef PROSE_DS_TABLES_H
#define PROSE_DS_TABLES_H

#include <stdint.h>

#if defined(__BYTE_ORDER__) && __BYTE_ORDER__ != __ORDER_LITTLE_ENDIAN__
#error "the data-segment tables are copied into the ROM image as they lie in memory: little-endian only"
#endif

#define PROSE_DS_DATA_BASE 0xF4100u /* linear address of DS:0000 */
#define PROSE_DS_SIZE 0xAEAAu       /* DS:0000-AEA9 is ROM data */
#define PROSE_DS_FNV1A64 0xFC86CABA8C589DDDull /* FNV-1a (64-bit) of the ROM's DS:0000-AEA9 */

/* compile-time check (C99) */
#define PROSE_DS_ASSERT(name, cond) typedef char prose_ds_assert_##name[(cond) ? 1 : -1]
/* a 16-bit value as two bytes, little-endian, inside a byte table */
#define PROSE_W(x) (uint8_t)((x) & 0xFF), (uint8_t)(((x) >> 8) & 0xFF)

/* where each table lies; prose_rom_builtin copies them into the ROM image (ds_layout.c) */
typedef struct {
	uint16_t off, size;
	const void *data;
	const char *name;
} prose_ds_span;
extern const prose_ds_span prose_ds_layout[];
extern const unsigned prose_ds_layout_count;

/* the tables, in DS order: offset, then the array (src/data/ds_<file>.c) */
#define PROSE_DS_RAW_0000 0x0000u
extern const uint8_t prose_ds_raw_0000[976];
#define PROSE_DS_RAW_03D0 0x03D0u
extern const uint8_t prose_ds_raw_03d0[7518];
#define PROSE_DS_RAW_212E 0x212Eu
extern const uint8_t prose_ds_raw_212e[12746];
#define PROSE_DS_RAW_52F8 0x52F8u
extern const uint8_t prose_ds_raw_52f8[3418];
#define PROSE_DS_RAW_6052 0x6052u
extern const uint8_t prose_ds_raw_6052[538];
#define PROSE_DS_RAW_626C 0x626Cu
extern const uint8_t prose_ds_raw_626c[14716];
#define PROSE_DS_RAW_9BE8 0x9BE8u
extern const uint8_t prose_ds_raw_9be8[4802];

#endif
